---

- name: "install dependencies"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"

- name: "add gpg key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: "verify fingerprint"
  apt_key:
    id: 0EBFCD88
    state: present

- name: "add repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"

- name: "install docker"
  apt:
    name: "docker-ce"
    update_cache: yes

- name: "create docker group"
  group:
    name: "{{ docker_group }}"
    state: present

- name: "add user to group"
  user:
    name: "{{ user }}"
    groups: "{{ docker_group }}"
    append: yes

- name: "create docker home directory"
  file:
    path: /home/{{ user }}/.docker
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "g+rwx"

- name: "install docker python package"
  shell: |
    pip3 install docker
  args:
    warn: false

- include_tasks: docker-compose.yml
