---

- name: "install packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "git"

- name: "config color.ui"
  git_config:
    name: color.ui
    scope: global
    value: auto
  become: true
  become_user: "{{ user }}"

- name: "config push.default"
  git_config:
    name: push.default
    scope: global
    value: simple
  become: true
  become_user: "{{ user }}"

- name: "config push.default"
  git_config:
    name: user.name
    scope: global
    value: test
  become: true
  become_user: "{{ user }}"

- name: "config push.default"
  git_config:
    name: user.email
    scope: global
    value: test@sujiakeji.com
  become: true
  become_user: "{{ user }}"
