---

- name: "create mysql data directory"
  file:
    path: "{{ mysql_data_path }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "docker"

- name: "create mysql container"
  docker_container:
    name: "sujiakeji-mysql"
    image: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - "{{ mysql_data_path }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "root"
