---

- name: "create config-repo project directory"
  file:
    path: "{{ workspace }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: "download config-repo project"
  git:
    repo: "{{ gitlab_host }}/sujiakeji/sujiakeji-config-repo.git"
    dest: "{{ workspace }}/sujiakeji-config-repo"
    force: yes
  become: true
  become_user: "{{ user }}"
