---

- name: "install packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "python3"
      - "python3-dev"
      - "python3-distutils"
      - "python3-wheel"
      - "python3-pip"
      - "python3-setuptools"

- name: "copy config file"
  copy:
    src: pip.conf
    dest: "/etc/pip.conf"

- name: "upgrade pip"
  shell: |
    pip3 install --upgrade pip
  args:
    warn: false
